# Generated by Django 5.2.14 on 2026-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='ticker',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
