# Generated by Django 5.2.14 on 2026-05-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_council_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
