# Generated by Django 5.2.14 on 2026-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_run_evidence_risk_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='investor_profile_applied',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
