# Generated by Django 5.2.14 on 2026-05-29 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0008_run_persona_evolution_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='rerun_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='runs.run'),
        ),
    ]
