# Generated by Django 5.2.14 on 2026-05-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0009_run_rerun_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='search_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
