# Generated by Django 5.2.14 on 2026-07-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0012_run_graph_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='max_budget_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
