"""Seed canonical ModelEntry rows on post_migrate."""
from __future__ import annotations

from decimal import Decimal

CANONICAL_MODELS = [
    # Anthropic frontier
    dict(id="anthropic:claude-sonnet-4-6", provider="anthropic",
         display_name="Claude Sonnet 4.6", tier="frontier",
         context_window=200_000, supports_caching=True,
         supports_long_context=True,
         price_in_per_mtok=Decimal("3.00"), price_out_per_mtok=Decimal("15.00")),
    dict(id="anthropic:claude-opus-4-7", provider="anthropic",
         display_name="Claude Opus 4.7", tier="frontier",
         context_window=200_000, supports_caching=True,
         supports_long_context=True,
         price_in_per_mtok=Decimal("15.00"), price_out_per_mtok=Decimal("75.00")),
    dict(id="anthropic:claude-haiku-4-5-20251001", provider="anthropic",
         display_name="Claude Haiku 4.5", tier="fast_cheap",
         context_window=200_000, supports_caching=True,
         supports_long_context=True,
         price_in_per_mtok=Decimal("1.00"), price_out_per_mtok=Decimal("5.00")),
    # OpenRouter hosted-open
    dict(id="openrouter:meta-llama/llama-3.3-70b-instruct", provider="openrouter",
         display_name="Llama 3.3 70B (OpenRouter)", tier="hosted_open",
         context_window=131_072, supports_long_context=True,
         price_in_per_mtok=Decimal("0.10"), price_out_per_mtok=Decimal("0.32")),
    dict(id="openrouter:qwen/qwen3.6-27b", provider="openrouter",
         display_name="Qwen3 27B (OpenRouter)", tier="hosted_open",
         context_window=131_072, supports_long_context=True,
         price_in_per_mtok=Decimal("0.30"), price_out_per_mtok=Decimal("3.20")),
    dict(id="openrouter:deepseek/deepseek-r1", provider="openrouter",
         display_name="DeepSeek R1 (OpenRouter)", tier="hosted_open",
         context_window=131_072, supports_long_context=True,
         price_in_per_mtok=Decimal("0.70"), price_out_per_mtok=Decimal("2.50")),
    # Cost-effective OpenRouter paid models picked for load + reasoning quality.
    # Pricing verified from openrouter.ai/api/v1/models; verify_openrouter_pricing
    # keeps these in sync.
    dict(id="openrouter:qwen/qwen3-235b-a22b-2507", provider="openrouter",
         display_name="Qwen3 235B A22B Instruct (OpenRouter)", tier="hosted_open",
         context_window=262_144, supports_long_context=True,
         price_in_per_mtok=Decimal("0.071"), price_out_per_mtok=Decimal("0.100")),
    dict(id="openrouter:openai/gpt-oss-120b", provider="openrouter",
         display_name="GPT-OSS 120B (OpenRouter)", tier="hosted_open",
         context_window=131_072, supports_long_context=True,
         price_in_per_mtok=Decimal("0.039"), price_out_per_mtok=Decimal("0.180")),
    dict(id="openrouter:nvidia/nemotron-3-nano-30b-a3b", provider="openrouter",
         display_name="NVIDIA Nemotron 3 Nano 30B A3B (OpenRouter)", tier="hosted_open",
         context_window=262_144, supports_long_context=True,
         price_in_per_mtok=Decimal("0.050"), price_out_per_mtok=Decimal("0.200")),
    dict(id="openrouter:mistralai/mistral-small-3.2-24b-instruct", provider="openrouter",
         display_name="Mistral Small 3.2 24B (OpenRouter)", tier="hosted_open",
         context_window=128_000, supports_long_context=True,
         price_in_per_mtok=Decimal("0.075"), price_out_per_mtok=Decimal("0.200")),
    dict(id="openrouter:google/gemma-3-27b-it", provider="openrouter",
         display_name="Gemma 3 27B (OpenRouter)", tier="hosted_open",
         context_window=131_072, supports_long_context=True,
         price_in_per_mtok=Decimal("0.080"), price_out_per_mtok=Decimal("0.160")),
    dict(id="openrouter:amazon/nova-lite-v1", provider="openrouter",
         display_name="Amazon Nova Lite 1.0 (OpenRouter)", tier="hosted_open",
         context_window=300_000, supports_long_context=True,
         price_in_per_mtok=Decimal("0.060"), price_out_per_mtok=Decimal("0.240")),
    dict(id="openrouter:deepseek/deepseek-v4-flash", provider="openrouter",
         display_name="DeepSeek V4 Flash (OpenRouter)", tier="hosted_open",
         context_window=1_048_576, supports_long_context=True,
         price_in_per_mtok=Decimal("0.100"), price_out_per_mtok=Decimal("0.200")),
    dict(id="openrouter:qwen/qwen3.5-flash-02-23", provider="openrouter",
         display_name="Qwen3.5 Flash (OpenRouter)", tier="hosted_open",
         context_window=1_000_000, supports_long_context=True,
         price_in_per_mtok=Decimal("0.065"), price_out_per_mtok=Decimal("0.260")),
    dict(id="openrouter:qwen/qwen3-coder-30b-a3b-instruct", provider="openrouter",
         display_name="Qwen3 Coder 30B A3B (OpenRouter)", tier="hosted_open",
         context_window=160_000, supports_long_context=True,
         price_in_per_mtok=Decimal("0.070"), price_out_per_mtok=Decimal("0.270")),
    dict(id="openrouter:z-ai/glm-4-32b", provider="openrouter",
         display_name="GLM 4 32B (OpenRouter)", tier="hosted_open",
         context_window=128_000, supports_long_context=True,
         price_in_per_mtok=Decimal("0.100"), price_out_per_mtok=Decimal("0.100")),
    # OpenRouter free-tier. price=0 is the "free" marker; the
    # verify_openrouter_pricing command keeps these in sync with OpenRouter
    # and stamps last_verified_at on every row.
    dict(id="openrouter:arcee-ai/trinity-large-thinking:free", provider="openrouter",
         display_name="Arcee Trinity Large (Thinking, OpenRouter Free)", tier="hosted_open",
         context_window=262_144, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
    dict(id="openrouter:nvidia/nemotron-3-super-120b-a12b:free", provider="openrouter",
         display_name="NVIDIA Nemotron 3 Super 120B (OpenRouter Free)", tier="hosted_open",
         context_window=1_000_000, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
    dict(id="openrouter:openai/gpt-oss-120b:free", provider="openrouter",
         display_name="GPT-OSS 120B (OpenRouter Free)", tier="hosted_open",
         context_window=131_072, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
    dict(id="openrouter:deepseek/deepseek-v4-flash:free", provider="openrouter",
         display_name="DeepSeek V4 Flash (OpenRouter Free)", tier="hosted_open",
         context_window=1_048_576, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
    dict(id="openrouter:qwen/qwen3-coder:free", provider="openrouter",
         display_name="Qwen3 Coder (OpenRouter Free)", tier="hosted_open",
         context_window=1_048_576, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
    dict(id="openrouter:minimax/minimax-m2.5:free", provider="openrouter",
         display_name="MiniMax M2.5 (OpenRouter Free)", tier="hosted_open",
         context_window=204_800, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
    dict(id="openrouter:google/gemma-4-31b-it:free", provider="openrouter",
         display_name="Gemma 4 31B (OpenRouter Free)", tier="hosted_open",
         context_window=262_144, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
    dict(id="openrouter:z-ai/glm-4.5-air:free", provider="openrouter",
         display_name="GLM 4.5 Air (OpenRouter Free)", tier="hosted_open",
         context_window=131_072, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
    dict(id="openrouter:poolside/laguna-m.1:free", provider="openrouter",
         display_name="Poolside Laguna M.1 (OpenRouter Free)", tier="hosted_open",
         context_window=131_072, supports_long_context=True,
         price_in_per_mtok=Decimal("0"), price_out_per_mtok=Decimal("0")),
]


def seed_models(sender, **kwargs):
    from .models import ModelEntry
    for spec in CANONICAL_MODELS:
        ModelEntry.objects.update_or_create(id=spec["id"], defaults=spec)
