# Generated by Django 5.2.14 on 2026-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('form_type', models.CharField(max_length=16)),
                ('filed_at', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('accession', models.CharField(max_length=32, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('text_excerpt', models.TextField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=6, max_digits=18)),
                ('high', models.DecimalField(decimal_places=6, max_digits=18)),
                ('low', models.DecimalField(decimal_places=6, max_digits=18)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('adjusted_close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('volume', models.BigIntegerField()),
                ('source', models.CharField(max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'date'], name='data_dailyb_ticker_66f530_idx')],
                'unique_together': {('ticker', 'date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Fundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('as_of_date', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('metric', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('source', models.CharField(max_length=32)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'as_of_date'], name='data_fundam_ticker_4f0fd4_idx')],
                'unique_together': {('ticker', 'period_end', 'metric', 'source')},
            },
        ),
    ]
