# Generated by Django 5.2.14 on 2026-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(unique=True)),
                ('growth_quadrant', models.CharField(max_length=16)),
                ('inflation_regime', models.CharField(max_length=16)),
                ('yield_curve_state', models.CharField(max_length=16)),
                ('policy_stance', models.CharField(max_length=16)),
                ('narrative', models.TextField()),
                ('sector_implications', models.JSONField(blank=True, default=dict)),
                ('series_used', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='filingrecord',
            name='full_text_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='filingrecord',
            name='section_index',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MacroSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('vintage_date', models.DateField(db_index=True)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['series_id', 'date', 'vintage_date'], name='data_macros_series__54d2e9_idx')],
                'unique_together': {('series_id', 'date', 'vintage_date')},
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('headline', models.CharField(max_length=512)),
                ('source', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('url', models.URLField(max_length=1000)),
                ('summary', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('materiality_score', models.FloatField(blank=True, null=True)),
                ('materiality_tag', models.CharField(blank=True, default='', max_length=32)),
                ('dedup_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'published_at'], name='data_newsit_ticker_55bcfa_idx')],
                'unique_together': {('provider', 'url')},
            },
        ),
    ]
