# Generated by Django 5.2.14 on 2026-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_p2b_macro_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('as_of_date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('split', 'Split'), ('cash_dividend', 'Cash dividend'), ('stock_dividend', 'Stock dividend'), ('symbol_change', 'Symbol change'), ('delisting', 'Delisting'), ('merger_cash', 'Cash merger')], max_length=24)),
                ('ratio', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('new_symbol', models.CharField(blank=True, default='', max_length=16)),
                ('source', models.CharField(max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'as_of_date', 'kind'], name='data_corpor_ticker_a39b32_idx')],
                'unique_together': {('ticker', 'as_of_date', 'kind', 'source')},
            },
        ),
    ]
