# Generated by Django 5.2.14 on 2026-05-21 13:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_corporateaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrosnapshot',
            name='markov_consensus',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('as_of_date', models.DateField(db_index=True)),
                ('model_type', models.CharField(choices=[('labelled_markov', 'Labelled Markov chain'), ('gaussian_hmm', 'Gaussian HMM')], default='labelled_markov', max_length=24)),
                ('config_hash', models.CharField(db_index=True, max_length=64)),
                ('return_window_days', models.SmallIntegerField(default=20)),
                ('bull_threshold_return', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=6)),
                ('bear_threshold_return', models.DecimalField(decimal_places=4, default=Decimal('-0.0500'), max_digits=6)),
                ('price_field', models.CharField(default='adjusted_close', max_length=24)),
                ('transition_matrix', models.JSONField()),
                ('state_means', models.JSONField(blank=True, null=True)),
                ('state_stds', models.JSONField(blank=True, null=True)),
                ('state_labels', models.JSONField()),
                ('stationary_distribution', models.JSONField()),
                ('fit_observations', models.IntegerField()),
                ('observations_available', models.IntegerField()),
                ('fit_lookback_observations', models.IntegerField(default=2520)),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('log_likelihood', models.FloatField(blank=True, null=True)),
                ('fit_metadata', models.JSONField(blank=True, default=dict)),
                ('fitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'as_of_date'], name='data_regime_ticker_ebd80a_idx')],
                'unique_together': {('ticker', 'as_of_date', 'model_type', 'config_hash')},
            },
        ),
        migrations.CreateModel(
            name='RegimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('as_of_date', models.DateField(db_index=True)),
                ('model_type', models.CharField(choices=[('labelled_markov', 'Labelled Markov chain'), ('gaussian_hmm', 'Gaussian HMM')], default='labelled_markov', max_length=24)),
                ('config_hash', models.CharField(db_index=True, max_length=64)),
                ('last_price_date', models.DateField()),
                ('current_state', models.CharField(max_length=12)),
                ('current_return', models.FloatField(blank=True, null=True)),
                ('current_state_persistence', models.FloatField()),
                ('bull_persistence', models.FloatField()),
                ('sideways_persistence', models.FloatField()),
                ('bear_persistence', models.FloatField()),
                ('bull_prob_1d', models.FloatField()),
                ('sideways_prob_1d', models.FloatField()),
                ('bear_prob_1d', models.FloatField()),
                ('bull_prob_5d', models.FloatField()),
                ('sideways_prob_5d', models.FloatField()),
                ('bear_prob_5d', models.FloatField()),
                ('bull_minus_bear_1d', models.FloatField()),
                ('prior_current_state', models.CharField(blank=True, default='', max_length=12)),
                ('current_state_persistence_delta', models.FloatField(blank=True, null=True)),
                ('bull_persistence_delta', models.FloatField(blank=True, null=True)),
                ('bear_persistence_delta', models.FloatField(blank=True, null=True)),
                ('state_changed_from_prior', models.BooleanField(default=False)),
                ('stale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prior_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='data.regimesnapshot')),
                ('source_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='data.regimemodel')),
            ],
            options={
                'indexes': [models.Index(fields=['as_of_date', 'model_type'], name='data_regime_as_of_d_e42ccb_idx'), models.Index(fields=['ticker', 'as_of_date'], name='data_regime_ticker_97c9e3_idx')],
                'unique_together': {('ticker', 'as_of_date', 'model_type', 'config_hash')},
            },
        ),
    ]
