# Generated by Django 5.2.14 on 2026-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_market_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketnewsitem',
            name='headline_en',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='marketnewsitem',
            name='language',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='marketnewsitem',
            name='summary_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marketnewsitem',
            name='translated_from',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='marketnewsitem',
            name='translation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketnewsitem',
            name='translation_model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='usernewspreferences',
            name='translation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernewspreferences',
            name='translation_fallback_model',
            field=models.CharField(default='openrouter:meta-llama/llama-3.3-70b-instruct', max_length=128),
        ),
        migrations.AddField(
            model_name='usernewspreferences',
            name='translation_model',
            field=models.CharField(default='openrouter:qwen/qwen3-235b-a22b-2507', max_length=128),
        ),
    ]
