# Generated by Django 5.2.14 on 2026-05-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_marketnewsitem_headline_en_marketnewsitem_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusipTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(max_length=12, unique=True)),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker'], name='data_cusipt_ticker_4323d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer_cik', models.CharField(db_index=True, max_length=20)),
                ('filer_name', models.CharField(blank=True, max_length=255)),
                ('issuer_cusip', models.CharField(db_index=True, max_length=12)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('ticker', models.CharField(blank=True, db_index=True, max_length=20)),
                ('period_end', models.DateField(db_index=True)),
                ('filed_at', models.DateField(blank=True, null=True)),
                ('shares', models.BigIntegerField(default=0)),
                ('value_usd', models.BigIntegerField(default=0)),
                ('put_call', models.CharField(blank=True, max_length=8)),
                ('source', models.CharField(default='edgar', max_length=16)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'period_end'], name='data_instit_ticker_6e2a3b_idx'), models.Index(fields=['filer_cik', 'period_end'], name='data_instit_filer_c_313221_idx'), models.Index(fields=['issuer_cusip', 'period_end'], name='data_instit_issuer__b6f4a5_idx')],
                'unique_together': {('filer_cik', 'issuer_cusip', 'period_end', 'put_call', 'source')},
            },
        ),
        migrations.CreateModel(
            name='IssuerOwnershipSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('issuer_cusip', models.CharField(blank=True, db_index=True, max_length=12)),
                ('period_end', models.DateField(db_index=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('num_holders', models.IntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('total_value_usd', models.BigIntegerField(default=0)),
                ('institutional_ownership_pct', models.FloatField(blank=True, null=True)),
                ('ownership_pct', models.FloatField(blank=True, null=True)),
                ('qoq_value_change_pct', models.FloatField(blank=True, null=True)),
                ('top_holders', models.JSONField(default=list)),
                ('new_positions', models.JSONField(default=list)),
                ('closed_positions', models.JSONField(default=list)),
                ('source', models.CharField(default='edgar', max_length=16)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'as_of_date'], name='data_issuer_ticker_066b68_idx')],
                'unique_together': {('ticker', 'period_end', 'source')},
            },
        ),
    ]
