# Generated by Django 6.0.8 on 2026-09-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_cusipticker_institutionalholding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="macrosnapshot",
            name="classifier_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
