# Generated by Django 6.0.8 on 2026-09-07 16:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_macrosnapshot_classifier_version"),
        ("hedgefund_agents", "0004_llmcall_portfolio_target"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsLlmUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("sentiment", "Sentiment"),
                            ("translation", "Translation"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "llm_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_llm_usage",
                        to="hedgefund_agents.llmcall",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_llm_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="data_newsll_user_id_9e5e66_idx",
                    )
                ],
            },
        ),
    ]
