# Generated by Django 6.0.8 on 2026-09-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_wave3_news_llm_usage"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cusipticker",
            name="data_cusipt_ticker_4323d7_idx",
        ),
        migrations.DeleteModel(
            name="CusipTicker",
        ),
        migrations.AlterUniqueTogether(
            name="institutionalholding",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="institutionalholding",
            name="data_instit_ticker_6e2a3b_idx",
        ),
        migrations.RemoveIndex(
            model_name="institutionalholding",
            name="data_instit_filer_c_313221_idx",
        ),
        migrations.RemoveIndex(
            model_name="institutionalholding",
            name="data_instit_issuer__b6f4a5_idx",
        ),
        migrations.DeleteModel(
            name="InstitutionalHolding",
        ),
        migrations.AlterUniqueTogether(
            name="issuerownershipsnapshot",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="issuerownershipsnapshot",
            name="data_issuer_ticker_066b68_idx",
        ),
        migrations.DeleteModel(
            name="IssuerOwnershipSnapshot",
        ),
    ]
