# Generated by Django 5.2.14 on 2026-05-30 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0025_remove_portfoliotarget_uniq_active_strategy_target_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(db_index=True, max_length=64)),
                ('agent_version', models.CharField(blank=True, default='', max_length=64)),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('window', models.CharField(max_length=16)),
                ('as_of', models.DateField(db_index=True)),
                ('n_decisions', models.IntegerField(default=0)),
                ('n_directional', models.IntegerField(default=0)),
                ('hit_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('hit_rate_ci_low', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('hit_rate_ci_high', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('brier_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('avg_forward_return_bps', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pnl_contribution_bps', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('provisional', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['window', 'as_of'], name='leaderboard_window_129c55_idx')],
                'constraints': [models.UniqueConstraint(fields=('agent_name', 'agent_version', 'model_id', 'window', 'as_of'), name='uniq_agent_scorecard')],
            },
        ),
        migrations.CreateModel(
            name='ModelScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(db_index=True, max_length=128)),
                ('agent_role', models.CharField(max_length=32)),
                ('window', models.CharField(max_length=16)),
                ('as_of', models.DateField(db_index=True)),
                ('n_decisions', models.IntegerField(default=0)),
                ('avg_cost_per_decision_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('avg_forward_return_bps', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_adjusted_return_bps', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('provisional', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['window', 'as_of'], name='leaderboard_window_346143_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_id', 'agent_role', 'window', 'as_of'), name='uniq_model_scorecard')],
            },
        ),
        migrations.CreateModel(
            name='StrategyScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=20)),
                ('window', models.CharField(max_length=16)),
                ('as_of', models.DateField(db_index=True)),
                ('n_cycles', models.IntegerField(default=0)),
                ('total_return_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('annualised_return_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sharpe', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('sortino', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('hit_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('annualised_turnover_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('avg_cost_per_cycle_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('council_alpha_bps', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('provisional', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='portfolios.portfoliostrategy')),
            ],
            options={
                'indexes': [models.Index(fields=['flavor', 'window', 'as_of'], name='leaderboard_flavor_92570e_idx')],
                'constraints': [models.UniqueConstraint(fields=('strategy', 'flavor', 'window', 'as_of'), name='uniq_strategy_scorecard')],
            },
        ),
    ]
