# Generated by Django 5.2.14 on 2026-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_strategyscorecard_baseline_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentscorecard',
            name='contrarian_hit_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agentscorecard',
            name='contrarian_hit_rate_ci_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agentscorecard',
            name='contrarian_hit_rate_ci_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agentscorecard',
            name='n_contrarian_decisions',
            field=models.IntegerField(default=0),
        ),
    ]
