# Generated by Django 5.2.14 on 2026-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_agentscorecard_contrarian_hit_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyscorecard',
            name='max_drawdown_p25_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='strategyscorecard',
            name='max_drawdown_p75_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='strategyscorecard',
            name='sharpe_p25',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='strategyscorecard',
            name='sharpe_p75',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='strategyscorecard',
            name='sortino_p25',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='strategyscorecard',
            name='sortino_p75',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
