# Generated by Django 6.0.8 on 2026-09-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0004_strategyscorecard_max_drawdown_p25_pct_and_more"),
        ("portfolios", "0037_p14_shared_pool_fund"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agentscorecard",
            name="uniq_agent_scorecard",
        ),
        migrations.RemoveConstraint(
            model_name="strategyscorecard",
            name="uniq_strategy_scorecard",
        ),
        migrations.AddField(
            model_name="agentscorecard",
            name="metrics_version",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="agentscorecard",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_scorecards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="strategyscorecard",
            name="metrics_version",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="strategyscorecard",
            name="n_observations",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="strategyscorecard",
            name="periods_per_year",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="strategyscorecard",
            name="sortino_note",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="strategyscorecard",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategy_scorecards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="agentscorecard",
            constraint=models.UniqueConstraint(
                fields=(
                    "user",
                    "agent_name",
                    "agent_version",
                    "model_id",
                    "window",
                    "as_of",
                ),
                name="uniq_agent_scorecard",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategyscorecard",
            constraint=models.UniqueConstraint(
                fields=("user", "strategy", "flavor", "window", "as_of"),
                name="uniq_strategy_scorecard",
            ),
        ),
    ]
