from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="Universe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("name", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("source", models.CharField(default="manual", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UniverseMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("sector", models.CharField(blank=True, default="", max_length=64)),
                ("effective_from", models.DateField(db_index=True)),
                ("effective_to", models.DateField(blank=True, db_index=True, null=True)),
                ("universe", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name="memberships", to="portfolios.universe")),
            ],
            options={
                "unique_together": {("universe", "ticker", "effective_from")},
                "indexes": [models.Index(fields=["universe", "ticker"],
                                          name="portfolios__universe_47e5cd_idx")],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("cash_balance", models.DecimalField(decimal_places=2, default=Decimal("100000"), max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name="portfolios", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("avg_cost", models.DecimalField(decimal_places=4, max_digits=12)),
                ("sector", models.CharField(blank=True, default="", max_length=64)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name="positions", to="portfolios.portfolio")),
            ],
            options={"unique_together": {("portfolio", "ticker")}},
        ),
        migrations.CreateModel(
            name="PortfolioStrategy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("target_gross_pct", models.DecimalField(decimal_places=2, default=Decimal("1.50"), max_digits=5)),
                ("target_net_pct", models.DecimalField(decimal_places=2, default=Decimal("0.50"), max_digits=5)),
                ("max_position_pct", models.DecimalField(decimal_places=4, default=Decimal("0.03"), max_digits=5)),
                ("max_sector_pct", models.DecimalField(decimal_places=4, default=Decimal("0.25"), max_digits=5)),
                ("min_position_pct", models.DecimalField(decimal_places=4, default=Decimal("0.005"), max_digits=5)),
                ("top_k_longs", models.IntegerField(default=10)),
                ("top_k_shorts", models.IntegerField(default=5)),
                ("personas", models.JSONField(blank=True, default=list)),
                ("model_preset", models.CharField(default="hybrid", max_length=16)),
                ("cost_ceiling_per_cycle_usd",
                 models.DecimalField(decimal_places=2, default=Decimal("5.00"), max_digits=8)),
                ("min_trade_notional_usd",
                 models.DecimalField(decimal_places=2, default=Decimal("250"), max_digits=10)),
                ("max_turnover_pct",
                 models.DecimalField(decimal_places=4, default=Decimal("0.30"), max_digits=5)),
                ("screener_weights", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                 to="portfolios.portfolio")),
                ("universe", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                to="portfolios.universe")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name="strategies", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="BorrowQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("as_of_date", models.DateField(db_index=True)),
                ("available_shares", models.IntegerField(blank=True, null=True)),
                ("fee_pct_annual", models.DecimalField(decimal_places=4, default=Decimal("0.01"), max_digits=6)),
                ("is_locatable", models.BooleanField(default=True)),
                ("source", models.CharField(default="stub", max_length=16)),
            ],
            options={"unique_together": {("ticker", "as_of_date", "source")}},
        ),
        migrations.CreateModel(
            name="ScreenerRanking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("as_of_date", models.DateField(db_index=True)),
                ("long_candidates", models.JSONField(default=list)),
                ("short_candidates", models.JSONField(default=list)),
                ("universe_size_evaluated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("strategy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name="rankings", to="portfolios.portfoliostrategy")),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("as_of_date", models.DateField()),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"),
                                                       ("done", "Done"), ("failed", "Failed")],
                                              default="queued", max_length=16)),
                ("target_weights", models.JSONField(default=dict)),
                ("gross_pct", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=5)),
                ("net_pct", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=6)),
                ("sector_exposure", models.JSONField(default=dict)),
                ("rejected_candidates", models.JSONField(default=list)),
                ("decisions", models.JSONField(default=list)),
                ("total_cost_usd", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=10)),
                ("error_message", models.TextField(blank=True, default="")),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("strategy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name="targets", to="portfolios.portfoliostrategy")),
                ("screener_ranking", models.ForeignKey(blank=True, null=True,
                                                         on_delete=django.db.models.deletion.SET_NULL,
                                                         to="portfolios.screenerranking")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["strategy", "-as_of_date"],
                                          name="portfolios__strateg_3a1f7c_idx")],
            },
        ),
        migrations.CreateModel(
            name="RebalanceOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("side", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell"),
                                                     ("short", "Short"), ("cover", "Cover")], max_length=8)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("limit_price", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("reason", models.CharField(choices=[("open", "Open"), ("resize_up", "Resize up"),
                                                       ("resize_down", "Resize down"), ("close", "Close"),
                                                       ("risk_reduce", "Risk reduce")], max_length=16)),
                ("estimated_notional_usd", models.DecimalField(decimal_places=2, default=Decimal("0"),
                                                                 max_digits=14)),
                ("sequence", models.IntegerField(default=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name="orders", to="portfolios.portfoliotarget")),
            ],
            options={"ordering": ["sequence", "ticker"]},
        ),
    ]
