# Generated by Django 5.2.14 on 2026-05-20 09:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_sector_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostrategy',
            name='min_aggregate_confidence',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.550'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='portfoliostrategy',
            name='min_positions',
            field=models.SmallIntegerField(default=3),
        ),
    ]
