# Generated by Django 5.2.14 on 2026-05-20 10:39

from decimal import Decimal
from django.db import migrations, models


def opt_out_legacy_sector_rotation(apps, schema_editor):
    """Pre-refinement sector_rotation strategies stay on v1 behaviour until the
    user explicitly opts in. New strategies inherit default=True."""
    Strategy = apps.get_model('portfolios', 'PortfolioStrategy')
    Strategy.objects.filter(kind='sector_rotation').update(use_sector_council_v2=False)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_relax_concentrated_long_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostrategy',
            name='bearish_veto_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.700'), max_digits=4),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='use_sector_council_v2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfoliotarget',
            name='sector_veto_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(opt_out_legacy_sector_rotation, noop),
    ]
