# Generated by Django 5.2.14 on 2026-05-21 13:06
#
# P2m — Markov regime exposure scaler + risk-parity gate fields on
# PortfolioStrategy. Pure additive change; no behavioural shift until
# regime_exposure_scaler is flipped on or enable_markov_regime_gate is set.

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0016_p2l_unified_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostrategy',
            name='enable_markov_regime_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='markov_bear_prob_5d_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.850'), max_digits=4),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='regime_exposure_scaler',
            field=models.CharField(choices=[('off', 'Off'), ('scale_net', 'Scale net'), ('scale_gross', 'Scale gross')], default='off', max_length=16),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='regime_scaler_allow_negative_net',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='regime_scaler_ceiling',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='regime_scaler_floor',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='regime_scaler_ticker',
            field=models.CharField(default='SPY', max_length=16),
        ),
    ]
