# Generated by Django 5.2.14 on 2026-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0027_p7_autonomous_fund'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='etfholdingsnapshot',
            new_name='portfolios__etf_tic_5973a2_idx',
            old_name='portf_etfsnap_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='portfolios__portfol_dcc502_idx',
            old_name='portf_ledger_portf_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='pair',
            new_name='portfolios__strateg_481eb3_idx',
            old_name='portfolios__strateg_4d39ea_idx',
        ),
        migrations.RenameIndex(
            model_name='pairzhistory',
            new_name='portfolios__pair_id_4011df_idx',
            old_name='portfolios__pair_id_b5d3c7_idx',
        ),
        migrations.AlterField(
            model_name='etfholdingsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='macroetf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='macroregimesnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pairzhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliopreferences',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliotargetrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectoretf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='volestimate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
