# Generated by Django 5.2.14 on 2026-06-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0028_rename_portf_etfsnap_idx_portfolios__etf_tic_5973a2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostrategy',
            name='risk_disclaimer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
