# Generated by Django 5.2.15 on 2026-06-09 19:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0031_alter_portfoliostrategy_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostrategy',
            name='enable_spy_regime_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='regime_gate_floor',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=4),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='rp_max_gross',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='portfoliostrategy',
            name='rp_vol_target_annual',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5),
        ),
    ]
