# Generated by Django 6.0.6 on 2026-06-11 07:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0032_portfoliostrategy_enable_spy_regime_gate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('net_flow', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('source', models.CharField(choices=[('sweep', 'Guardrail sweep'), ('backfill', 'Broker history backfill'), ('manual', 'Manual')], default='sweep', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['portfolio', 'date'], name='portfolios__portfol_370148_idx')],
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
