# Generated by Django 5.2.15 on 2026-07-07 12:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0033_p10_portfolio_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostrategy',
            name='rp_max_equity_pct',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4),
        ),
    ]
