# Generated by Django 5.2.15 on 2026-07-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0034_portfoliostrategy_rp_max_equity_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostrategy',
            name='allow_short',
            field=models.BooleanField(default=False),
        ),
    ]
