# Generated by Django 5.2.15 on 2026-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0035_portfoliostrategy_allow_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliostrategy',
            name='kind',
            field=models.CharField(choices=[('long_only', 'Long-only'), ('short_only', 'Short-only'), ('long_short', 'Long/Short'), ('market_neutral', 'Market-neutral'), ('concentrated_long', 'Concentrated long-only'), ('sector_rotation', 'Sector / thematic ETF rotation'), ('global_macro', 'Global macro (ETF expression)'), ('risk_parity', 'Risk-parity / multi-asset lite'), ('pairs', 'Pairs trading (cointegration)'), ('trend', 'Deterministic trend (TSMOM)'), ('sector_momentum', 'Deterministic sector momentum'), ('news_sentiment', 'News-sentiment single-name (council overlay)'), ('xsec_long_short', 'Single-name L/S (cross-sectional) — scaffolding, needs survivorship-clean data')], default='long_short', max_length=20),
        ),
    ]
