# Generated by Django 6.0.8 on 2026-09-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0037_p14_shared_pool_fund"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fund_halt", "Fund halted"),
                            ("fund_resume", "Fund resumed"),
                            ("guardrail_transition", "Guardrail state transition"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="portfolios.autonomousfund",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fund_events",
                        to="portfolios.portfoliostrategy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["fund", "-created_at"],
                        name="portfolios__fund_id_514124_idx",
                    )
                ],
            },
        ),
    ]
