# Generated by Django 5.2.14 on 2026-05-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0001_initial'),
        ('hedgefund_agents', '0002_agentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcall',
            name='backtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='backtests.backtest'),
        ),
    ]
