# Generated by Django 5.2.14 on 2026-05-19 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedgefund_agents', '0003_llmcall_backtest'),
        ('portfolios', '0002_rename_portfolios__strateg_3a1f7c_idx_portfolios__strateg_2f6e5c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcall',
            name='portfolio_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='portfolios.portfoliotarget'),
        ),
    ]
