# Generated by Django 5.2.14 on 2026-05-23 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nudge_dismiss_count', models.PositiveSmallIntegerField(default=0)),
                ('nudge_last_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('apply_to_runs', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('questionnaire', 'Questionnaire'), ('tuned', 'Tuned')], default='questionnaire', max_length=14)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('answers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_id', models.CharField(max_length=128)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('profile_summary', models.TextField(blank=True, default='')),
                ('agent_brief', models.TextField(blank=True, default='')),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tunes', to='investor_profile.questionnaireresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='investor_pr_user_id_45c6a1_idx'), models.Index(fields=['user', 'analysis_status'], name='investor_pr_user_id_d81a80_idx')],
            },
        ),
    ]
