# Generated by Django 5.2.14 on 2026-05-30 02:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('runs', '0009_run_rerun_of'),
        ('watchlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('personas', models.JSONField(blank=True, default=list)),
                ('model_preset', models.CharField(default='hybrid', max_length=32)),
                ('model_overrides', models.JSONField(blank=True, default=dict)),
                ('cron_expression', models.CharField(max_length=64)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('is_market_aware', models.BooleanField(default=True)),
                ('cost_ceiling_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('on_breach', models.CharField(choices=[('degrade', 'Degrade to a cheaper preset'), ('skip', 'Skip the run'), ('notify_only', 'Run anyway and notify about the overage')], default='degrade', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='notifications.notificationchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_runs', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_runs', to='watchlists.watchlist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledRunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_time_utc', models.DateTimeField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('actual_cost_usd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('degraded_preset', models.CharField(blank=True, default='', max_length=32)),
                ('materiality_decision', models.JSONField(blank=True, default=dict)),
                ('notified_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('runs', models.ManyToManyField(blank=True, related_name='schedule_history', to='runs.run')),
                ('scheduled_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='schedules.scheduledrun')),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('scheduled_run', 'fire_time_utc'), name='uniq_schedule_fire_time')],
            },
        ),
    ]
