# Generated by Django 5.2.14 on 2026-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledrun',
            name='model_preset',
            field=models.CharField(default='frugal', max_length=32),
        ),
    ]
