# Generated by Django 5.2.14 on 2026-05-30 16:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_alter_brokeraccount_id_alter_brokercredential_id_and_more'),
        ('schedules', '0002_alter_scheduledrun_model_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledrun',
            name='auto_paper_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='auto_submit_broker_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_submit_schedules', to='brokers.brokeraccount'),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='auto_submit_draft_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='max_notional_per_day_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='max_orders_per_day',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='scheduledrunhistory',
            name='broker_orders',
            field=models.ManyToManyField(blank=True, related_name='scheduled_histories', to='brokers.brokerorder'),
        ),
        migrations.AddField(
            model_name='scheduledrunhistory',
            name='submit_decision',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
