# Generated by Django 5.2.14 on 2026-06-01 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
        ('schedules', '0003_scheduledrun_auto_paper_submit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledrun',
            name='graph_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='graphs.agentgraphversion'),
        ),
    ]
