# Generated by Django 5.2.14 on 2026-06-01 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_graphs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentGraphVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('tail_models', models.JSONField(default=dict)),
                ('validation_status', models.CharField(default='draft_invalid', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='graphs.agentgraph')),
            ],
            options={
                'ordering': ['graph_id', '-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentgraph',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_graph_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='agentgraphversion',
            constraint=models.UniqueConstraint(fields=('graph', 'version'), name='uniq_version_per_graph'),
        ),
    ]
