from django.urls import path

from .views import (
    BrokerAccountAckDriftView,
    BrokerAccountCredentialsView,
    BrokerAccountDisconnectView,
    BrokerAccountListCreateView,
    BrokerAccountOAuthCallbackView,
    BrokerAccountOAuthStartView,
    BrokerAccountOverviewView,
    BrokerAccountSyncView,
    BrokerOrderCancelView,
    BrokerOrderConfirmView,
    BrokerOrderListCreateView,
    BrokerRegistryView,
    CurrentDisclaimerView,
    DisclaimerAcceptView,
    MarketCalendarView,
)

urlpatterns = [
    path("brokers/", BrokerRegistryView.as_view(), name="brokers-registry"),
    path("brokers/calendar/", MarketCalendarView.as_view(), name="brokers-calendar"),
    path("broker-accounts/", BrokerAccountListCreateView.as_view(),
         name="broker-accounts"),
    path("broker-accounts/oauth/callback/",
         BrokerAccountOAuthCallbackView.as_view(),
         name="broker-account-oauth-callback"),
    path("broker-accounts/<int:account_id>/overview/",
         BrokerAccountOverviewView.as_view(), name="broker-account-overview"),
    path("broker-accounts/<int:account_id>/credentials/",
         BrokerAccountCredentialsView.as_view(),
         name="broker-account-credentials"),
    path("broker-accounts/<int:account_id>/oauth/start/",
         BrokerAccountOAuthStartView.as_view(),
         name="broker-account-oauth-start"),
    path("broker-accounts/<int:account_id>/disconnect/",
         BrokerAccountDisconnectView.as_view(),
         name="broker-account-disconnect"),
    path("broker-accounts/<int:account_id>/sync/",
         BrokerAccountSyncView.as_view(), name="broker-account-sync"),
    path("broker-accounts/<int:account_id>/acknowledge-drift/",
         BrokerAccountAckDriftView.as_view(),
         name="broker-account-ack-drift"),

    path("broker/orders/", BrokerOrderListCreateView.as_view(),
         name="broker-orders"),
    path("broker/orders/<int:order_id>/confirm/",
         BrokerOrderConfirmView.as_view(), name="broker-order-confirm"),
    path("broker/orders/<int:order_id>/cancel/",
         BrokerOrderCancelView.as_view(), name="broker-order-cancel"),

    path("disclaimers/current/", CurrentDisclaimerView.as_view(),
         name="disclaimers-current"),
    path("disclaimers/accept/", DisclaimerAcceptView.as_view(),
         name="disclaimers-accept"),
]
