from django.urls import path

from .views import (
    BrokerAccountAckDriftView,
    BrokerAccountCredentialsView,
    BrokerAccountDeleteView,
    BrokerAccountDisconnectView,
    BrokerAccountListCreateView,
    BrokerAccountOAuthCallbackView,
    BrokerAccountOAuthStartView,
    BrokerAccountOverviewView,
    BrokerAccountSyncView,
    BrokerGatewayActivateView,
    BrokerGatewayAuthStatusView,
    BrokerGatewayDiscoverAccountsView,
    BrokerGatewayProbeView,
    BrokerOrderCancelView,
    BrokerOrderConfirmView,
    BrokerOrderListCreateView,
    BrokerRegistryView,
    CurrentDisclaimerView,
    DisclaimerAcceptView,
    IBKRRuntimeConfigView,
    MarketCalendarView,
    TradeStationActivateView,
    TradeStationAppCredentialsView,
    TradeStationDiscoverAccountsView,
    TradeStationRuntimeConfigView,
)

urlpatterns = [
    path("brokers/", BrokerRegistryView.as_view(), name="brokers-registry"),
    path("brokers/calendar/", MarketCalendarView.as_view(), name="brokers-calendar"),
    path("broker-accounts/", BrokerAccountListCreateView.as_view(),
         name="broker-accounts"),
    path("broker-accounts/oauth/callback/",
         BrokerAccountOAuthCallbackView.as_view(),
         name="broker-account-oauth-callback"),
    # P3a-2: IBKR gateway-session wizard. The /ibkr/ literal goes before
    # the <int:account_id> patterns so the int converter doesn't try to
    # match "ibkr".
    path("broker-accounts/ibkr/runtime-config/",
         IBKRRuntimeConfigView.as_view(), name="ibkr-runtime-config"),
    # P3a-3: TradeStation post-OAuth wizard. The /tradestation/ literal
    # goes before the <int:account_id> patterns just like /ibkr/ does.
    path("broker-accounts/tradestation/runtime-config/",
         TradeStationRuntimeConfigView.as_view(),
         name="tradestation-runtime-config"),
    path("broker-accounts/tradestation/app-credentials/",
         TradeStationAppCredentialsView.as_view(),
         name="tradestation-app-credentials"),
    path("broker-accounts/<int:account_id>/tradestation/discover-accounts/",
         TradeStationDiscoverAccountsView.as_view(),
         name="broker-account-tradestation-discover"),
    path("broker-accounts/<int:account_id>/tradestation/activate/",
         TradeStationActivateView.as_view(),
         name="broker-account-tradestation-activate"),
    path("broker-accounts/<int:account_id>/gateway/probe/",
         BrokerGatewayProbeView.as_view(),
         name="broker-account-gateway-probe"),
    path("broker-accounts/<int:account_id>/gateway/auth-status/",
         BrokerGatewayAuthStatusView.as_view(),
         name="broker-account-gateway-auth-status"),
    path("broker-accounts/<int:account_id>/gateway/discover-accounts/",
         BrokerGatewayDiscoverAccountsView.as_view(),
         name="broker-account-gateway-discover"),
    path("broker-accounts/<int:account_id>/gateway/activate/",
         BrokerGatewayActivateView.as_view(),
         name="broker-account-gateway-activate"),
    path("broker-accounts/<int:account_id>/overview/",
         BrokerAccountOverviewView.as_view(), name="broker-account-overview"),
    path("broker-accounts/<int:account_id>/credentials/",
         BrokerAccountCredentialsView.as_view(),
         name="broker-account-credentials"),
    path("broker-accounts/<int:account_id>/oauth/start/",
         BrokerAccountOAuthStartView.as_view(),
         name="broker-account-oauth-start"),
    path("broker-accounts/<int:account_id>/",
         BrokerAccountDeleteView.as_view(),
         name="broker-account-delete"),
    path("broker-accounts/<int:account_id>/disconnect/",
         BrokerAccountDisconnectView.as_view(),
         name="broker-account-disconnect"),
    path("broker-accounts/<int:account_id>/sync/",
         BrokerAccountSyncView.as_view(), name="broker-account-sync"),
    path("broker-accounts/<int:account_id>/acknowledge-drift/",
         BrokerAccountAckDriftView.as_view(),
         name="broker-account-ack-drift"),

    path("broker/orders/", BrokerOrderListCreateView.as_view(),
         name="broker-orders"),
    path("broker/orders/<int:order_id>/confirm/",
         BrokerOrderConfirmView.as_view(), name="broker-order-confirm"),
    path("broker/orders/<int:order_id>/cancel/",
         BrokerOrderCancelView.as_view(), name="broker-order-cancel"),

    path("disclaimers/current/", CurrentDisclaimerView.as_view(),
         name="disclaimers-current"),
    path("disclaimers/accept/", DisclaimerAcceptView.as_view(),
         name="disclaimers-accept"),
]
