# Generated by Django 5.2.14 on 2026-06-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_brokeraccount_default_quantity_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerorder',
            name='leg_role',
            field=models.CharField(blank=True, choices=[('entry', 'Entry'), ('stop_loss', 'Stop loss'), ('take_profit', 'Take profit')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='brokerorder',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_legs', to='brokers.brokerorder'),
        ),
        migrations.AddField(
            model_name='brokerorder',
            name='trail_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='brokerorder',
            name='trail_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='brokerorder',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop limit'), ('trailing_stop', 'Trailing stop')], default='market', max_length=16),
        ),
    ]
