# Generated by Django 5.2.14 on 2026-06-04 15:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_brokerorder_bracket_legs'),
        ('portfolios', '0026_portfoliotarget_council_alpha_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerorder',
            name='rebalance_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_orders', to='portfolios.rebalanceorder'),
        ),
        migrations.AddField(
            model_name='brokerorder',
            name='release_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brokerorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('submitted', 'Submitted'), ('partial', 'Partial fill'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('error', 'Error'), ('pending_open', 'Pending market open')], default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='StrategyBrokerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_usd', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_links', to='brokers.brokeraccount')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_links', to='portfolios.portfoliostrategy')),
            ],
            options={
                'indexes': [models.Index(fields=['broker_account', 'is_active'], name='brokers_str_broker__b12b17_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('strategy',), name='uniq_active_broker_link_per_strategy')],
            },
        ),
    ]
