# Generated by Django 6.0.8 on 2026-09-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brokers", "0007_brokerorder_sleeve"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerorder",
            name="submit_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
