# Generated by Django 5.2.14 on 2026-06-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona_evolution', '0003_profile_current_cycle_started_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='personaevolutionrevision',
            new_name='persona_evo_profile_48b04b_idx',
            old_name='persona_evo_profile_4ad6c7_idx',
        ),
    ]
