# Generated by Django 5.2.14 on 2026-05-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_catalog', '0003_modelentry_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerkey',
            name='resend_api_key_enc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='providerkey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usermodelpreferences',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
