# Generated by Django 5.2.14 on 2026-06-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_catalog', '0006_delete_deepseek_r1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('tier_name', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('is_free_only', models.BooleanField(default=False)),
                ('price_ceiling_in', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_ceiling_out', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('allow_reasoning', models.BooleanField(default=False)),
                ('is_live_synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='models_catalog.modelentry')),
            ],
        ),
        migrations.CreateModel(
            name='TierMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
                ('role', models.CharField(blank=True, default='', max_length=24)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_memberships', to='models_catalog.modelentry')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='models_catalog.tierconfig')),
            ],
            options={
                'ordering': ['ordering', 'model_id'],
                'unique_together': {('tier', 'model')},
            },
        ),
    ]
