# Generated by Django 5.2.14 on 2026-06-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_catalog', '0007_tierconfig_tiermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelpreferences',
            name='per_tier_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
