# Generated by Django 5.2.14 on 2026-05-17 19:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=128, unique=True)),
                ('agent_name', models.CharField(db_index=True, max_length=64)),
                ('agent_version', models.CharField(max_length=32)),
                ('response_json', models.JSONField(default=dict)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('hits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('universe', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('starting_cash', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=18)),
                ('commission_bps', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('spread_bps', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('agent_graph_version', models.CharField(default='council-v1', max_length=64)),
                ('agent_versions', models.JSONField(blank=True, default=dict)),
                ('model_overrides', models.JSONField(blank=True, default=dict)),
                ('personas', models.JSONField(blank=True, default=list)),
                ('rebalance_frequency', models.CharField(default='weekly', max_length=16)),
                ('is_window_days', models.IntegerField(default=252)),
                ('oos_window_days', models.IntegerField(default=63)),
                ('step_days', models.IntegerField(default=63)),
                ('search_space', models.JSONField(blank=True, default=dict)),
                ('n_candidates', models.IntegerField(default=50)),
                ('is_objective', models.CharField(default='sharpe', max_length=16)),
                ('rng_seed', models.IntegerField(default=42)),
                ('baseline', models.CharField(default='universe_ew', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress_pct', models.IntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.TextField(blank=True, default='')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BacktestFold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fold_index', models.IntegerField()),
                ('is_start', models.DateField()),
                ('is_end', models.DateField()),
                ('oos_start', models.DateField()),
                ('oos_end', models.DateField()),
                ('winning_config', models.JSONField(blank=True, default=dict)),
                ('is_sharpe', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('oos_sharpe', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('oos_return_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('oos_max_drawdown_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('candidates_scored', models.JSONField(blank=True, default=list)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folds', to='backtests.backtest')),
            ],
            options={
                'ordering': ['fold_index'],
                'unique_together': {('backtest', 'fold_index')},
            },
        ),
        migrations.CreateModel(
            name='BacktestMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_return_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('annualized_return_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sharpe', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sortino', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('max_drawdown_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('hit_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('win_loss_ratio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('turnover_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('mean_is_sharpe', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('mean_oos_sharpe', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('sharpe_deflation', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('oos_sharpe_std', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('baseline_return_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('per_agent_attribution', models.JSONField(blank=True, default=dict)),
                ('backtest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='backtests.backtest')),
            ],
        ),
        migrations.CreateModel(
            name='BacktestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(default='oos', max_length=8)),
                ('date', models.DateField(db_index=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('positions', models.JSONField(default=list)),
                ('portfolio_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='backtests.backtest')),
                ('fold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='backtests.backtestfold')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['backtest', 'segment', 'date'], name='backtests_b_backtes_05c138_idx')],
            },
        ),
    ]
