# Generated by Django 5.2.14 on 2026-05-18 13:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='max_budget_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('aborted_budget', 'Aborted (budget)')], default='queued', max_length=16),
        ),
    ]
