# Generated by Django 5.2.14 on 2026-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0002_backtest_max_budget_usd_alter_backtest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='hold_semantics',
            field=models.CharField(default='hold_existing', max_length=16),
        ),
        migrations.AddField(
            model_name='backtest',
            name='prime_completeness',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='backtest',
            name='prime_min_completeness',
            field=models.FloatField(default=0.85),
        ),
        migrations.AddField(
            model_name='backtestday',
            name='fills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('aborted_budget', 'Aborted (budget)'), ('aborted_partial', 'Aborted (sparse data)'), ('synthetic', 'Synthetic')], default='queued', max_length=16),
        ),
    ]
