# Generated by Django 5.2.14 on 2026-05-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0003_backtest_hold_semantics_backtest_prime_completeness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='prime_completeness',
            field=models.FloatField(default=0.0),
        ),
    ]
