# Generated by Django 5.2.14 on 2026-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0004_prime_completeness_default_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='disable_cio',
            field=models.BooleanField(default=True),
        ),
    ]
