# Generated by Django 5.2.14 on 2026-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0005_disable_cio_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='prime_min_completeness',
            field=models.FloatField(default=0.65),
        ),
    ]
