# Generated by Django 5.2.14 on 2026-06-01 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0006_prime_min_completeness_default_065'),
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='graph_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='graphs.agentgraphversion'),
        ),
    ]
