# Generated by Django 5.2.14 on 2026-06-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0007_backtest_graph_version'),
        ('portfolios', '0026_portfoliotarget_council_alpha_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='portfolios.portfoliostrategy'),
        ),
    ]
