# Generated by Django 5.2.14 on 2026-06-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0008_p7_autonomous_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='engine_mode',
            field=models.CharField(
                choices=[
                    ('council', 'Council (LLM vote)'),
                    ('risk_parity', 'Deterministic risk parity'),
                ],
                default='council',
                max_length=20,
            ),
        ),
    ]
