# Generated by Django 5.2.15 on 2026-06-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0009_backtest_engine_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='engine_mode',
            field=models.CharField(choices=[('council', 'Council (LLM vote)'), ('risk_parity', 'Deterministic risk parity'), ('trend', 'Deterministic trend (TSMOM)'), ('sector_momentum', 'Deterministic sector momentum')], default='council', max_length=20),
        ),
    ]
