# Generated by Django 6.0.6 on 2026-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0012_p10_era_seed_candidates_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
