# Generated by Django 5.2.15 on 2026-07-07 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0013_p10_backtest_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='financing_bps',
            field=models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=6),
        ),
    ]
