# Generated by Django 5.2.15 on 2026-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0014_backtest_financing_bps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='engine_mode',
            field=models.CharField(choices=[('council', 'Council (LLM vote)'), ('risk_parity', 'Deterministic risk parity'), ('trend', 'Deterministic trend (TSMOM)'), ('sector_momentum', 'Deterministic sector momentum'), ('xsec_long_short', 'Single-name cross-sectional long/short')], default='council', max_length=20),
        ),
    ]
